name: WakaTime Coding Statistics

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 5 * * *'

jobs:
  update-Readme:
    name: Automatically update my README  
    runs-on: ubuntu-latest
    steps:
      - uses: tariksahni/coding-stats-wakatime@v1.0.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          REPO_TOKEN: ${{ github.token }}

